#!/usr/bin/env bash

# ---------- #
# install.sh #
# ---------- #

# Install script for dotbot

set -e

CONFIG="config/install.conf.yaml"
DOTBOT_DIR="tools/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir tools/dotbot-plugins/dotbot-asdf -c "${CONFIG}" "${@}"
# "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir tools/dotbot-plugins/dotbot-vscode -c "${CONFIG}" "${@}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# EOF #
