#
# beets `config.yaml`
# see: https://beets.readthedocs.io/en/stable/reference/config.html
#

# example config:
# -----------------------------------------------------------
# directory: /var/mp3
# import:
#     copy: yes
#     write: yes
#     log: beetslog.txt
# art_filename: albumart
# plugins: bpd
# pluginpath: ~/beets/myplugins
# ui:
#     color: yes
#
# paths:
#     default: $genre/$albumartist/$album/$track $title
#     singleton: Singletons/$artist - $title
#     comp: $genre/$album/$track $title
#     albumtype:soundtrack: Soundtracks/$album/$track $title
#
# -----------------------------------------------------------

import:
    write: yes
    move: yes
plugins: discogs fromfilename edit fetchart embedart
ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

# EOF
